dbt_basic2:
  outputs:
    dev:
      dataset: dbt_project1
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: optical-empire-412502
      threads: 60
      type: bigquery
  target: dev
